User.destroy_all
Brewery.destroy_all
Product.destroy_all
Post.destroy_all

# Post.create(title: Faker::GreekPhilosophers.quote, content: Faker::Hipster.paragraph, brewery_id: Faker::Number.between(21,26))

b1 = Brewery.create(name: 'Beavertown', bio: "Founded in 2011 by Logan Plant in the basement of a pub the brewery has grown up and become one of the flagship London breweries around. Taking its name from the old cockney name for the Victorian part of London De Beauvoir they quickly out grew the basement of Dukes Brew and Que and relocated to Hackney Wick. After a short time there they realised they needed to grow again and made a final move over to Tottenham Hale in North London. There they have perfected such brews as Gamma Ray and gained a loyal fan base for their modern and forward thinking beers.", location: 'London', profile_img: Faker::Avatar.image)
b2 = Brewery.create(name: 'Magic Rock',bio: "Magic Rock Brewing Co. is the result of three peoples passion for beer. Brothers Richard and Jonny Burhouse* aided by head brewer Stuart Ross were inspired to start the brewery by their love of great beer and the burgeoning U.S craft beer scene in particular. Driven by a desire to bring exciting characterful beers to their local market and beyond, brewing commenced mid 2011. *Jonny sold the majority of his shareholding to Richard in late 2011.", location: 'Huddersfield', profile_img: Faker::Avatar.image)
b3 = Brewery.create(name: 'Cloudwater', bio: "An exciting brewery based in Manchester, Cloudwater are out to put Northern British brewing on the world map. Their beers are exciting and new bringing together British brewing knowledge with a passion for new brewing techniques and flavours. They use hops in interesting ways to bring out undertones in their beers that other brewers might have missed. With a drive to be an innovative brewery they invite the drinker to be discerning with their choice of brew and offer a range of beers suited to all who want to find taste and creativity in their beer.", location: 'Manchester', profile_img: Faker::Avatar.image)
b4 = Brewery.create(name: 'Lost and Grounded', bio: "Starting life in 2016 this Bristol brewer gained an instant reputation for being one of the best in the UK. With Alex Troncoso and Annie Clements at the helm it was never going to be bad. Alex was part of shaping Little Creatures into where it is today, and helped to build Camden Town Brewery into the monster that was eventually bought out, which is when this brewer of excellence and his partner left to follow their dream of their own brewery.", location: 'Bristol', profile_img: Faker::Avatar.image)
b5 = Brewery.create(name: 'Left Handed Giant', bio: "Left Handed Giant began a few years ago as the brain-child of Bruce Gray. For their first few years they were brewing on a small-scale, with most of their beer going straight into the legendary Small bar in Bristol. in late 2017 however they opened their all singing, all dancing new brewery and the beers being released these days are out of this world.", location: 'Bristol', profile_img: Faker::Avatar.image)
b6 = Brewery.create(name: 'Brick Brewery', bio: "Starting from our humble roots in a Peckham shed, since 2013 we have been building our brewery in a railway arch in Peckham Rye, SE London. Every recipe is built from scratch, our Tapyard was built by our fair hands (with a little bit of help from our mate Matt), hell we even built our own urinals! Inspired by our travels, the beers we build are varied and showcase the diversity of beers from around the world.", location: 'London', profile_img: Faker::Avatar.image)
b7 = Brewery.create(name: 'Brew By Numbers', bio: "Brew By Numbers were born in 2012 in the heart of Bermondsey brew mile. Known for brewing experimental versions of traditional styles they have cemented themselves as one of the best London craft breweries. Drawing inspiration from various countries and experiences, they use each ingredient to maximum effect brewing a base beer, splitting it down and using different hops in the boil and yeast in the fermenter to create fantastic versions of each brew.", location: 'London', profile_img: Faker::Avatar.image)
b8 = Brewery.create(name: 'Gipsy Hill', bio: "One of the younger London brewers but growing fast thanks to their focus on lower ABV brews with big flavours, this London brewery stands out by making beers that are just so damn moreish. On top of their core range they also make fantastic, experimental seasonals that have earned them a very deserved reputation.", location: 'London', profile_img: Faker::Avatar.image)


Product.create(name: 'Bloody \'Ell', description: "Beavertown Bloody 'Ell is upon us! This IPA is a seasonal release, and sought by beer nerds and hop heads all over the world. Brewed with an unhealthy dose of New World hops, the massive citrus flavours are given an even bigger boost by the addition of blood oranges. It's juicy, fruity and properly bitter and pithy.", abv: 5.5, volume: 330, style: 'IPA', packaging: 'can', price: 3.10, stock: 20, image_url: '', brewery_id: b1.id)
Product.create(name: 'Neck Oil', description: "Beavertown’s Session IPA Neck Oil pack a huge amount of flavour into a light, refreshing beer. It is crammed full of hops that are added a different times during the brew to bring out their individual flavours while reducing the bitterness. It starts out very dry to taste that is then quickly overtaken by the floral fruity notes of the hops before a dry, hoppy full-flavoured finish that makes a mockery of its low abv.", abv: 4.3, volume: 330, style: 'IPA', packaging: 'can', price: 2.65, stock: 20, image_url: '', brewery_id: b1.id)
Product.create(name: 'Gamma Ray', description: "A genre-defining American pale ale that’s made in London! Beavertown’s signature beer is all about the hops, and from the moment you crack the beer open you can smell them. Fruity, zesty and floral, every kind of hop aroma is there, dominated by the tropical fruit and citrus. The sweet malt background is light enough to let those massive hops shine throughout the beer, especially in the finish when all those heady aromas come back for a rasping dry finish.", abv: 5.4, volume: 330, style: 'Pale Ale', packaging: 'can', price: 2.90, stock: 20, image_url: '', brewery_id: b1.id)
Product.create(name: 'Black Betty', description: "Black IPAs are big, hoppy IPAs brewed with a small amount of chocolate and roasted malt to add a little sweetness and a roasted coffee edge. Somewhere between a porter and an IPA, Beavertown’s Black Betty has a big tropical fruit aroma tempered with burnt toast and liquorice to make for a complex and warming beer.", abv: 7.0, volume: 330, style: 'IPA', packaging: 'can', price: 3.50, stock: 20, image_url: '', brewery_id: b1.id)
Product.create(name: 'Lupuloid', description: "The culmination of months of experimentation and test brews this is the ultimate Lupuliod. The 1st permanent Beavertown IPA and it is very gladly here to stay. Coming in at a booming 6.7% this is a superbly crafted beer that has a big tropical aroma and a good solid malt body leading to a fruity dry hop character which is then well rounded off by the yeast. Ending with a dry lasting finish this is one of the best IPAs to ever come out of the UK.", abv: 6.7, volume: 330, style: 'IPA', packaging: 'can', price: 3.25, stock: 20, image_url: '', brewery_id: b1.id)

Product.create(name: 'Saucery', description: "A supernatural session IPA made for drinking all day long. Lightly sweet and malty Golden Promise™ malt, a balanced bitterness and layers of tropical fruit filled Citra and Ekuanot hops in whirlpool and dry hop. Fermented with London Ale II yeast to add more fruity body, and enhance malt and hop profile", abv: 3.9, volume: 330, style: 'IPA', packaging: 'can', price: 2.35, stock: 20, image_url: '', brewery_id: b2.id)
Product.create(name: 'Recency Effect', description: "A classically contemporary West Coast IPA in collaboration with friends over at Buxton Brewery. True to style the beer has punchy aromatics, moreish drinkability and a defined bitterness. They've used rye and a light crystal malt to add a satisfying complexity to the malt profile and then sack loads of fruity, dank and piney US hops in whirlpool and dry hop. Fermented with California ale yeast for minimal flavor interference.", abv: 7.0, volume: 500, style: 'IPA', packaging: 'can', price: 4.70, stock: 20, image_url: '', brewery_id: b2.id)
Product.create(name: 'Big Dipper', description: "A revisit of their collaborative Double IPA brew with friends from over t’hills Cloudwater Brew Co. Golden Promise, Wheat, Oat and Crystal Malt were used for a smooth, golden, malty body. A combination of Citra, Simcoe, Eureka and Mosaic T90 hops were used in the whirlpool and dry hopping, with additional Citra & Mosaic LupulN2 Pellets added in the dry hop. Fermented with London Fog yeast, the result is a fruit-filled DIPA with loads of Mango and Peach aroma/flavor, a little residual sweetness and a gravity-defying drinkability. Strap yourself in!!", abv: 8.2, volume: 500, style: 'IPA', packaging: 'can', price: 5.30, stock: 20, image_url: '', brewery_id: b2.id)
Product.create(name: 'Like Us Lil Soleil', description: "While Rune from People Like Us was on his collaboration tour, he came to make a beer with the guys at Magic Rock and they brewed a Grapefruit & Pineapple Brut based on the recipe for a ‘Soleil’ Champagne cocktail that they've called Lil’ Soleil.", abv: 5.8, volume: 500, style: 'Pale Ale', packaging: 'can', price: 4.55, stock: 20, image_url: '', brewery_id: b2.id)
Product.create(name: 'Rode Goos', description: "Our old pal Kees from Brouwerij Kees stopped by for this fruited version of that classic German Wheat beer style Gose. Using our tried and tested Salty Kiss method we fermented with German ale yeast and went big on the fruit with Pomegranate, Cherry and Lemon additions to deliver a deeply fruity and deeply pink beer with a light acidic tang and balanced tart finish.", abv: 6.0, volume: 330, style: 'Sour', packaging: 'can', price: 3.25, stock: 20, image_url: '', brewery_id: b2.id)
Product.create(name: 'Bourbon BA De Mole', description: "A dark and broody British stout. This beer gives you all the sensations you want from a stout. Big chocolate malts with slight coffee flavours and a little dryness on the finish. The mouth feel is big and round creating a nice finish to a good beer.", abv: 10.0, volume: 330, style: 'Stout', packaging: 'can', price: 5.35, stock: 20, image_url: '', brewery_id: b2.id)
Product.create(name: 'Strongman Rye BA Barleywine', description: "Magic Rock's sumptuous Barley Wine ‘Strongman’ has been re-designed since its first outing 2011. They increased the complexity of the malt bill to include wheat malt, crystal rye, light crystal and aromatic malt in addition to their house Golden Promise. This additional malt has added a depth of satisfying malty character and layers of toffee and dried fruit. The beer has been carefully aged in freshly emptied Rye Whiskey casks until its ready to take the stage.", abv: 11.5, volume: 750, style: 'Barleywine', packaging: 'bottle', price: 16.45, stock: 20, image_url: '', brewery_id: b2.id)

Product.create(name: 'IPA', description: "Juicy, soft, and full of ripe tropical fruit flavours from a blend of hops and aromatic yeast, this IPA is our modern take on a classic style. Showcasing hop flavours and yeast esters against a big body from high protein malts, to replicate the mouthfeel of tropical fruit, this beer finishes with a low bitterness to let the hop aromas and flavours linger on your palate.", abv: 6.5, volume: 440, style: 'IPA', packaging: 'can', price: 5.55, stock: 20, image_url: '', brewery_id: b3.id)
Product.create(name: 'Hoppy Little Lager', description: "This clean, delicate beer sits somewhere between a Pale Ale and a Lager - an ideal, easy-drinker for nights out with friends, or just moments where you’re craving a beer but need to keep it moving afterwards. Bright citrus flavours lead into a crisp finish with a restrained, zesty bitterness.", abv: 3.8, volume: 440, style: 'Lager', packaging: 'can', price: 3.20, stock: 20, image_url: '', brewery_id: b3.id)
Product.create(name: 'Barry from Finance', description: "For the eighth in a series of collaborations celebrating their first festival, Friends & Family & Beer, Cloudwater teamed up with their good friends The Veil to bring you something a little different. This sour DIPA is loaded with pineapple and passion fruit, with an addition of orange zest. It's thick, sweet and juicy, yet still tart and refreshing.", abv: 8.0, volume: 440, style: 'IPA', packaging: 'can', price: 8.90, stock: 20, image_url: '', brewery_id: b3.id)
Product.create(name: 'Vienna Lager AW18', description: "This Vienna Lager features Munich malt for a deep malt flavour, balanced by orange-forward Loral hops in the kettle and as a light dry hop during fermentation. We fermented with a German Bock yeast for its clean flavour and crisp finish.", abv: 5.2, volume: 440, style: 'Lager', packaging: 'can', price: 4.25, stock: 20, image_url: '', brewery_id: b3.id)
Product.create(name: 'Helles AW18', description: "Helles is a classic German-style pale lager, popularised in Bavaria. It is a style that is subtle, delicate and designed to showcase malt flavours, with a crisp finish and very little hop bitterness. A long lagering period is used to achieve a beer that is bright, clean and refreshing.", abv: 4.8, volume: 440, style: 'lager', packaging: 'can', price: 3.60, stock: 20, image_url: '', brewery_id: b3.id)
Product.create(name: 'DDH Pale AW18', description: "This all-season DDH Pale provides a balance between a juicy, full-bodied IPA and easy drinking Pale. 'DDH' means this Pale has been double dry hopped, using twice the amount of hops as Cloudwater's standard Pale. It delivers big citrus fruit flavours and a smooth body, with a juicy tang and a peppery character on the finish.", abv: 5.5, volume: 440, style: 'Pale Ale', packaging: 'can', price: 4.85, stock: 20, image_url: '', brewery_id: b3.id)

Product.create(name: 'All the Cool Cats', description: "Well, it was eventually going to happen! Lost & Groundeds super-fresh, super-gentle unfiltered Helles is here! Brewed with German Pils malt and a low dose of Perle and Mittelfruh to make a smooth, bready and uber-balanced lager. A perfect match for the Spring sun, this lager is a delight!", abv: 5.1, volume: 440, style: 'Lager', packaging: 'can', price: 3.50, stock: 20, image_url: '', brewery_id: b4.id)
Product.create(name: 'Get Up and Boogie', description: "Lost and Grounded brewed this Berliner-style Weisse beer with a massive 70% wheat malt and soured with thier in-house lactic culture to make a tart, refreshing and thirst-quenching beer - perfect for the dancefloor! Get Up and Boogie has a fruity and tropical aroma, it's uber tasty and very sessionable.", abv: 3.8, volume: 440, style: 'Sour', packaging: 'can', price: 3.50, stock: 20, image_url: '', brewery_id: b4.id)
Product.create(name: 'Check Ignition', description: "Lost & Grounded Check Ignition, a fantastic porter with a perfect mix of Raspberry & Cooa Nib!", abv: 5.4, volume: 440, style: 'Stout', packaging: 'can', price: 3.75, stock: 20, image_url: '', brewery_id: b4.id)
Product.create(name: 'Hop-Hand Fallacy', description: "A refreshing and funky farmhouse ale. This brew has a really good amount of carbonation that allows the tastes to dance around on the palate. The beer has a spicy nose that gives way to a savoury taste in the mouth and a wonderfully dry and refreshing finish.", abv: 4.4, volume: 440, style: 'Saison', packaging: 'can', price: 3.50, stock: 20, image_url: '', brewery_id: b4.id)
Product.create(name: 'Donkey Vote', description: "Donkey Vote is a Märzen, the predecessor to the original Oktoberfest-style beers: the malty and biscuity character from huge whacks of Munich and Vienna malts combines perfectly with the cool fermentation and long maturation, producing a smooth and delicious lager beer. Hints of hops balance it all out.", abv: 5.2, volume: 440, style: 'Lager', packaging: 'can', price: 3.60, stock: 20, image_url: '', brewery_id: b4.id)
Product.create(name: 'Big Thaw', description: "West Coast-style IPA brewed in collaboration with our friends Burnt Mill! Hopped with a classic combo of Columbus, Chinook, Cascade, Centennial and Simcoe, with Pils and Caramalts. Think piney and citrusy aroma, coupled with a resinous, pithy bitterness. Delicious!", abv: 6.8, volume: 440, style: 'IPA', packaging: 'can', price: 4.40, stock: 20, image_url: '', brewery_id: b4.id)

Product.create(name: 'Cheeseburger Cavalry', description: "Cheeseburger Cavalry is not only a superb name, but a truly incredible IPA to boot. Layers of mango, papaya and ripe peach flavours over fresh citrus, underpinned by a well balanced malt bill as well as having some great bitterness underneath it all. This is a hazy IPA without being murky and we love it!", abv: 6.8, volume: 550, style: 'IPA', packaging: 'can', price: 5.85, stock: 20, image_url: '', brewery_id: b5.id)
Product.create(name: 'Every Single Thing', description: "Sour IPA with Passionfruit & lactose. Hopped with Mosaic, Galaxy & Vic Secret", abv: 5.8, volume: 440, style: 'Sour', packaging: 'can', price: 5.35, stock: 20, image_url: '', brewery_id: b5.id)
Product.create(name: 'Flight Risk', description: "Flight Risk is a delicious oatmeal stout from Bristol's finest. Brewed with Almond, Raspberry and Blueberry, this is an absolute delight.", abv: 6.8, volume: 440, style: 'Stout', packaging: 'can', price: 5.85, stock: 20, image_url: '', brewery_id: b5.id)
Product.create(name: 'Safe By Night', description: "A bit fo a departure from the usual hop-bombs LHG are famous for, but no less impressive. This classic Saison is generously hopped with Perle, Styrian Goldings & Saaz and brewed with a touch of Rye.", abv: 6.0, volume: 440, style: 'Saison', packaging: 'can', price: 4.15, stock: 20, image_url: '', brewery_id: b5.id)
Product.create(name: 'Get Got', description: "A 4.4% pale brewed with Columbus, Citra, Chinook and Centennial. We also used the yeast BRY 97 and experimented with dry hopping timings and rates to see how hop oils and active yeast interact with each other.", abv: 4.4, volume: 440, style: 'Pale Ale', packaging: 'can', price: 4.25, stock: 20, image_url: '', brewery_id: b5.id)

Product.create(name: 'Winter Berry Sour', description: "Their 5th Birthday celebration. Sour cherries, elderberries, blackcurrants and blackberries are added to the sour base before being aged on cherrywood and oak.", abv: 7.2, volume: 330, style: 'Sour', packaging: 'can', price: 3.65, stock: 20, image_url: '', brewery_id: b6.id)
Product.create(name: 'Rye', description: "An Amber Ale with 18% Rye malt to add a dry and biscuit quality to the beer.", abv: 5.0, volume: 330, style: 'Amber', packaging: 'can', price: 3.00, stock: 20, image_url: '', brewery_id: b6.id)
Product.create(name: 'Peckham Pils', description: "Peckham Pils is a Czech style pilsner. Light and refreshing. Made with Magnum & Saaz hops", abv: 4.8, volume: 330, style: 'Lager', packaging: 'can', price: 3.00, stock: 20, image_url: '', brewery_id: b6.id)
Product.create(name: 'Packham Pale', description: "Extra pale malt is blended with Munich, Vienna and a splash of Crystal malt to produce a light golden colour.", abv: 4.5, volume: 330, style: 'Pale Ale', packaging: 'can', price: 2.90, stock: 20, image_url: '', brewery_id: b6.id)
Product.create(name: 'Orange and Fennel Imperial Stout', description: "The combination of herbal fennel seed and zesty orange blends to complement the rich and deep stout base.", abv: 9.0, volume: 330, style: 'Stout', packaging: 'can', price: 4.05, stock: 20, image_url: '', brewery_id: b6.id)
Product.create(name: 'Blackcurrant and Sumac Sour', description: "Naturally sweet and tart Blackcurrants give a great depth to the soured base, the addition of Sumac lifts the beer with its touch of salinity and citrus.", abv: 3.6, volume: 330, style: 'Sour', packaging: 'can', price: 3.35, stock: 20, image_url: '', brewery_id: b6.id)

Product.create(name: '85|01 Triple IPA', description: "Brew By Numbers very first TIPA builds on the continued success of thier latest DIPAs. This is an intensely hopped modern IPA using new harvest Mosaic, El Dorado & Calypso in pellet and cyro pellet forms in the highest quantities they have ever used. The result: A aromatic cyclone of mango, melon and pineapple, followed by a massive wave of tropical juice, bitter grapefruit and swells of warming alcohols.", abv: 10.0, volume: 440, style: 'IPA', packaging: 'can', price: 7.55, stock: 20, image_url: '', brewery_id: b7.id)
Product.create(name: '18|10 Farmhouse Citra Triple', description: "Another superb mixed fermentation beer from brew by Numbers, this time putting their farmhouse blend into a Belgian style tripel. This is brewed using 100% Citra to accentuate the lemon sherbet notes from the brett and lift the funkier undertones.", abv: 9.9, volume: 750, style: 'Belgian', packaging: 'bottle', price: 10.95, stock: 20, image_url: '', brewery_id: b7.id)
Product.create(name: '01|30 Old Tom Gin', description: "Brew By Numbers has married our traditional saison recipe with Old Tom gin from their good friend's at Jenson's distillery to create an incredibly aromatic Belgian Ale. Their house yeast pairs perfectly with Jenson's blend of botanicals, ushering in a refreshing taste of spring.", abv: 5.0, volume: 440, style: 'Saison', packaging: 'can', price: 4.05, stock: 20, image_url: '', brewery_id: b7.id)
Product.create(name: '05 IPA Chinook and Mosaic', description: "Pine and citrus: the defining character of American IPAs. The Chinook & Mosaic hops of the Pacific Northwest USA are the embodiment of this.", abv: 6.2, volume: 440, style: 'IPA', packaging: 'can', price: 4.75, stock: 20, image_url: '', brewery_id: b7.id)
Product.create(name: '23 Keller Pils Loral', description: "A delicious unfiltered German-style Pilsner dry hopped liberally with Loral. Expect a crisp and floral flavour with a fruity kick.", abv: 4.8, volume: 440, style: 'Lager', packaging: 'can', price: 4.35, stock: 20, image_url: '', brewery_id: b7.id)
Product.create(name: '11 Session IPA Mosaic', description: "All the hop character of an India Pale Ale, crammed into a low ABV beer. Mosaic hops take centre stage in this recipe.", abv: 4.2, volume: 440, style: 'IPA', packaging: 'can', price: 4.20, stock: 20, image_url: '', brewery_id: b7.id)

Product.create(name: 'Hepcat', description: "Never has a session IPA been so balanced and yet so tasty before. This beer showcases the malts well giving a biscuit base and then the hops just build in a juicy, fruity kind of way. It is super refreshing and makes you reach for another the second your finished with the 1st one.", abv: 4.6, volume: 330, style: 'IPA', packaging: 'can', price: 2.80, stock: 20, image_url: '', brewery_id: b8.id)
Product.create(name: 'Beatnik', description: "A fruity and surprising pale ale from London. It has a tropical nose that is peppered with floral notes and a light spice. The taste is citrus, passion fruit and a little pine all of this is propped up ably by the clean and fresh malt build.", abv: 3.8, volume: 330, style: 'Pale Ale', packaging: 'can', price: 2.60, stock: 20, image_url: '', brewery_id: b8.id)
Product.create(name: 'Southpaw', description: "A sweet and malty amber ale with a deceptively punchy mouth feel and a juicy tropical hop profile. It is truly a modern amber beer that doesn't just present malts to you but a bag load of hops too. The start is a little sweet but the finish is big and dry.", abv: 4.2, volume: 330, style: 'Amber', packaging: 'can', price: 2.70, stock: 20, image_url: '', brewery_id: b8.id)
Product.create(name: 'Zazel Framboise', description: "Zazel is a Framboise-style kettle sour. Packed full of raspberries, it's a sweet and jammy with a puckering tartness.", abv: 5.0, volume: 440, style: 'Sour', packaging: 'can', price: 4.30, stock: 20, image_url: '', brewery_id: b8.id)
Product.create(name: 'Percolator', description: "This is a can of Percolator. Percolator is a collaboration with Dugges. It’s a Café Latte of a beer. Full of three different oats, premium English Cara and Vienna, it’s then been blended with close to a 1000 litres of Volcano’s finest cold brew coffee. It offers smooth, full-bodied mouthfuls of oat milk latte coffee.", abv: 5.0, volume: 440, style: 'Belgian', packaging: 'can', price: 4.55, stock: 20, image_url: '', brewery_id: b8.id)
Product.create(name: 'Kosmonaut', description: "Pitch black in colour with a creamy head, if you're looking for a great classic stout, Kosmonaut is the one! Kosmonaut comes it at 4.4% and uses Chocolate, Black and Roasted malt to give a dry base, all lifted by Pilgrim, First Gold and Tettnang hops.", abv: 4.4, volume: 440, style: 'Stout', packaging: 'can', price: 3.65, stock: 20, image_url: '', brewery_id: b8.id)